def teacher_handler(handler):
    if handler.command == "GET":
        ...
    elif handler.command == "POST":
        ...
    elif handler.command == "PUT":
        ...
    elif handler.command == "DELETE":
        ...